### ISSUE TITLE
SHA1 Deprecated messages

### ISSUE THREAD

**Issue by PeterWAWood** [mesca/homebrew-luarocks#1]
Thanks to your helpful instructions in the read.me I was able to successfully install luarocks to work with LuaJIT.

When I was installing them, brew printed a lot of messages about SHA1 being deprecated. Here's one of them:

```
Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/mesca/homebrew-luarocks/luarocks51.rb:7:in `<class:Luarocks51>'
Please report this to the mesca/luarocks tap!
```

**Comment by mesca** [comment]
Thank you for your contribution. This should now be fixed.
